# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kwf_weighted_average_cpp <- function(curves, weights) {
    .Call(`_elcf4R_kwf_weighted_average_cpp`, curves, weights)
}

