# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kwf_weighted_average_cpp <- function(curves, weights) {
    .Call(`_elcf4R_kwf_weighted_average_cpp`, curves, weights)
}

kwf_row_distances_cpp <- function(features, target) {
    .Call(`_elcf4R_kwf_row_distances_cpp`, features, target)
}

kwf_gaussian_kernel_weights_cpp <- function(distances, bandwidth = NULL) {
    .Call(`_elcf4R_kwf_gaussian_kernel_weights_cpp`, distances, bandwidth)
}

kwf_apply_group_restriction_cpp <- function(weights, context_groups, target_group) {
    .Call(`_elcf4R_kwf_apply_group_restriction_cpp`, weights, context_groups, target_group)
}

kwf_mean_corrected_forecast_cpp <- function(detail_future, approx_transitions, current_approx, weights) {
    .Call(`_elcf4R_kwf_mean_corrected_forecast_cpp`, detail_future, approx_transitions, current_approx, weights)
}

